import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import { ordered as cakeOrdered } from '../cake/cakeSlice'

type InitialState = {
    numOfIcecreams: number
}

const initialState: InitialState = {
    numOfIcecreams: 20
}

const icecreamSlice = createSlice({
    name: 'icecreams',
    initialState,
    reducers: {
        ordered: (state) => {
            state.numOfIcecreams--
        },
        restocked: (state, action: PayloadAction<number>) => {
            state.numOfIcecreams += action.payload
        }
    },

    // One way to use extraReducers
    //extraReducers: {    //extraReducers allows us to use actions from other slices that are not generated by default with this slice. Let's assume with every cake ordered, an icecream will be given as rewards. Though the iceCream reducers can access to the cake/orddered action, but it can only update it's own state, i.e. numOfIceCreams.
        //['cake/ordered']: (state) => {
        //    state.numOfIcecreams--
        //}
    //}

    // Recommended way of using extraReducer is using Build function
    extraReducers: (builder) => {
        builder.addCase(cakeOrdered, (state) => {
            state.numOfIcecreams--
        })
    }
})

export default icecreamSlice.reducer
export const { ordered, restocked } = icecreamSlice.actions